#!/usr/bin/env python3
"""Audit every quantitative claim in the docs against the generated results.

WHY THIS EXISTS
---------------
This repository makes a promise: the numbers in its prose come from
`results/portfolio.json`, and anyone can check. That promise decays silently.
The moment somebody re-runs the pipeline -- a seed changes, a threshold moves,
a probe is rewritten -- every figure typed into a spec, an ADR or a protocol
becomes a claim about a run that no longer exists. Nothing errors. The
documents still read as confident and internally consistent; they are simply
describing a different experiment.

Prose and results drift apart by default, and the only defence that survives
contact with a deadline is a mechanical one. So: extract every numeric literal
from the documentation, extract every number that appears anywhere in the
generated results, and require that the first set is contained in the second.
Numbers that legitimately do not come from results -- rubric weights, published
reference values, pre-registered thresholds, dates -- must be named explicitly
in ALLOWLIST below, each with a written justification. An allowlist entry
without a justification is just a silenced alarm, so the justification is
mandatory rather than decorative.

The script is itself a portfolio artifact. A repository that claims its numbers
are traceable should be able to prove it on demand:

    PYTHONPATH=src python3 scripts/audit_numbers.py     # or: make audit

Exit code 0 means every number in the docs traces to the current results or to
a justified allowlist entry. Exit code 1 means at least one does not.

HOW IT WORKS
------------
1.  Load `results/portfolio.json` and `results/sensitivity.json`, and collect
    every number appearing anywhere in them -- including numbers embedded
    inside strings, because the pipeline writes a great deal of its evidence as
    prose ("alpha=0.584 supports ..."). `sensitivity.json` is a first-class
    source: it is generated by the same pipeline, from the same corpus, by
    `make sensitivity`, and the documents quote it for every statement about
    how conditional a verdict is. Allowlisting those figures instead would have
    exempted the newest and least-reviewed numbers in the repository from the
    only check on them.
2.  Expand that into a value set with the derived forms a document would
    plausibly quote: the raw value, its percentage form (x*100), and its
    halved form (CI half-widths are routinely quoted where the results record
    a full width), each rounded to 0-4 decimal places.
3.  Walk every `.md` file under `docs/` (plus `README.md`), strip the regions
    where numbers are not claims -- fenced code blocks, table alignment rows,
    heading and list ordinals, ADR filenames, identifier-embedded digits -- and
    extract what is left.
4.  Look each literal up in the value set at its own precision: a figure
    written to three decimals must equal some results value rounded to three
    decimals.
5.  Anything still unmatched is checked against ALLOWLIST. Anything that
    survives that is reported, with its line number and surrounding text.

Note the ordering in steps 4 and 5: the cheap structural exclusions (code
blocks, list markers) run before the lookup, but the *value-based* exclusions
(years, allowlist) run only against numbers that already failed to match. A
number that genuinely traces to the results is never quietly written off as a
year or an allowlist hit, so the allowlist cannot hide a live figure.

WHAT THIS CANNOT CATCH
----------------------
Stated plainly, because a check whose limits are not written down gets trusted
past them.

The audit is set membership, not provenance. It asks "does this number exist
somewhere in the results?", not "does this number mean what the sentence says
it means". `portfolio.json` currently holds about 1,500 distinct values; once
percentage and halved forms are included, roughly 80 percent of the three-
decimal grid on [0,1] is occupied. So a figure quoted to two or three decimals
can pass by coincidence -- matching a per-item mean from a different track
rather than the quantity the prose names. Precision is the defence: a
four-decimal figure has about a one-in-five chance of an accidental hit, and
counts and integers are usually unambiguous.

Two things follow. Quote figures at four decimals where the results record
them at four. And treat a clean run as the floor it is: it proves no figure in
the docs is *absent* from the current results, not that every figure is
attached to the right claim. Semantic checking needs the number and its
referent to be extracted together, which is a bigger project than this file.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

# --------------------------------------------------------------------------
# ALLOWLIST
# --------------------------------------------------------------------------
#
# Numbers that are legitimately quoted in the documentation but do not, and
# should not, appear in `results/portfolio.json`. Two kinds of key:
#
#   "0.75"        an exact numeric literal, allowed wherever it appears
#   "re:<regex>"  a line pattern; numbers on a matching line are allowed
#
# Every entry carries a justification. That is the whole point of the
# mechanism: an unexplained allowlist entry is indistinguishable from a bug
# somebody wanted to stop hearing about. If you find yourself adding an entry
# to make a stale figure go away, fix the figure instead.

ALLOWLIST: dict[str, str] = {
    # -- Rubric structure: sourced from src/rubricon/tracks/agentic.py --------
    # Dimension weights and level counts are properties of the instrument, not
    # of a run. portfolio.json records the rubric's content-addressed version
    # string but not its weights, so these can only be checked against the
    # track module. They are stable across runs by construction: any change to
    # them changes the rubric hash, which the docs also quote.
    "re:^Weights \\(from `agentic\\.py`\\)": (
        "Rubric dimension weights (goal_completion 3.0, argument_fidelity 2.0, "
        "tool_selection 1.5, error_recovery 1.25, state_tracking 1.0, efficiency "
        "0.75). Declared in src/rubricon/tracks/agentic.py; not serialised into "
        "portfolio.json."
    ),
    "re:^### 4\\.\\d+ ": (
        "Per-dimension section headings quote that dimension's level range and "
        "weight (e.g. 'levels 0-4, weight 3.0'). Instrument structure from "
        "src/rubricon/tracks/agentic.py."
    ),
    "re:^\\| [0-4] \\| ": (
        "Rubric anchor tables: the leading cell is the level value and the row "
        "is the anchor text for that level. Instrument content from "
        "src/rubricon/tracks/agentic.py, not a measurement."
    ),
    "re:^\\*\\*Worked (positive|negative)": (
        "Worked scoring examples in the annotation guidelines. The numbers are "
        "illustrative rubric levels and fixture values (record IDs, amounts, "
        "HTTP codes) drawn from the task fixtures in "
        "src/rubricon/tracks/agentic.py, not results."
    ),
    "re:^Boundaries: ": (
        "Boundary-case rulings in the annotation guidelines: illustrative "
        "rubric levels and fixture values, not results."
    ),
    "re:^\\*\\*6\\.\\d+ |^Ruling: |^`dedupe_csv`|^A short script|^takes the hit|"
    "^`\\[\\]` as confirmation|^ambiguity and stopping|^same behaviour is|"
    "^`goal_completion` 2 if|^not promote to|^of blame\\.|^timezone appears|"
    "^case is a PO number|^`efficiency` 0 \\(identical|^`goal_completion` scored": (
        "Section 6 hard-case rulings: every number is a prescribed rubric level "
        "or a fixture value from the worked scenario. Instrument content."
    ),
    "re:^The 0-versus-1 boundary|^`po_number=|^even if it is the wrong PO|^level 1: wrong|"
    "^Correct account_id|^\\(identifying field\\)|^Why the threshold is 0": (
        "argument_fidelity 0-vs-1 boundary discussion: rubric levels and fixture "
        "identifiers/amounts, not results."
    ),
    "re:^\\*\\*Applying the gate twice|^\\*\\*Scoring the task|^run that gets there|"
    "^`argument_fidelity` 0 with |^\\*\\*Drifting over a long session|"
    "^your scores cluster|^Break every": (
        "Section 7 common-error guidance: prescribed rubric levels and a "
        "protocol break interval, not measurements."
    ),
    "re:^1\\. \\*\\*Read the prompt|^2\\. \\*\\*Read the final message|"
    "^3\\. \\*\\*Read the trace|^4\\. \\*\\*Second pass|^5\\. \\*\\*Compare the final|"
    "^underneath shows an invented|^Work in this order": (
        "Section 2 reading procedure: step ordinals and an illustrative HTTP "
        "status code in the motivating example. Protocol text, not results."
    ),
    "re:^\\*\\*Step \\d ": (
        "Section 3 order-of-operations steps: step ordinals and prescribed "
        "rubric levels. Protocol text, not results."
    ),
    "re:^Dimensions: 6\\. Failure codes: 13\\. Replication: 3": (
        "Instrument shape (6 dimensions, 13 failure codes, replication 3) "
        "declared in src/rubricon/tracks/agentic.py. The realised replication "
        "(3.00) is checked separately against portfolio.json."
    ),
    "0.75": (
        "efficiency dimension weight, and the lazy-baseline probe tolerance. "
        "Both are declared constants (tracks/agentic.py, redteam/probes.py), "
        "not run outputs."
    ),
    "1.25": "error_recovery dimension weight, declared in tracks/agentic.py.",
    "1.5": "tool_selection dimension weight, declared in tracks/agentic.py.",

    # -- Published reference values ------------------------------------------
    "0.743": (
        "Krippendorff's published worked-example alpha (nominal). Used by "
        "`make validate` as an external correctness check on the agreement "
        "implementation; it is a literature value, not a run output."
    ),
    "0.815": (
        "Krippendorff's published worked-example alpha (ordinal). Literature "
        "reference value used to validate the agreement implementation."
    ),
    "0.849": (
        "Krippendorff's published worked-example alpha (interval). Literature "
        "reference value used to validate the agreement implementation."
    ),
    "0.797": (
        "Krippendorff's published worked-example alpha (ratio). Literature "
        "reference value used to validate the agreement implementation."
    ),
    "0.7434": (
        "This implementation's reproduction of Krippendorff's published nominal "
        "alpha, asserted against the literature fixture in tests/conftest.py. It "
        "is a test output, not a portfolio field."
    ),
    "0.8154": (
        "Reproduction of Krippendorff's published ordinal alpha; asserted in "
        "tests/test_agreement.py against the literature fixture."
    ),
    "0.8491": (
        "Reproduction of Krippendorff's published interval alpha; asserted "
        "against the literature fixture in tests/conftest.py."
    ),
    "0.7974": (
        "Reproduction of Krippendorff's published ratio alpha; asserted against "
        "the literature fixture in tests/conftest.py."
    ),
    "0.002": (
        "Test tolerance (`TOL` in tests/test_agreement.py) for the agreement "
        "implementation against the published reference values."
    ),
    "225": (
        "Size of the test suite, from pytest collection over tests/ "
        "(`python3 -m pytest tests/ -q --collect-only`). A property of the "
        "repository, not of a pipeline run; portfolio.json has no field for it."
    ),
    "0.0004": (
        "Largest observed absolute deviation between this implementation's "
        "Krippendorff alpha and the published 2011 values (0.7434 vs 0.743, "
        "0.8154 vs 0.815, 0.7974 vs 0.797; interval deviates by only 0.0001). "
        "Derived from the test fixture outputs, not a portfolio field."
    ),
    "0.667": (
        "Krippendorff's tentative-conclusion threshold. A published guidance "
        "value, adopted as GatePolicy.alpha_warn_below."
    ),
    "0.800": (
        "Krippendorff's firm-conclusion threshold. A published guidance value, "
        "adopted as GatePolicy.alpha_firm_at."
    ),
    "0.20": (
        "Landis-Koch band boundary (slight/fair), and GatePolicy."
        "max_empty_cell_fraction. Published band boundary and pre-registered "
        "threshold; neither is measured."
    ),
    "0.40": "Landis-Koch band boundary (fair/moderate). Published reference value.",
    "0.60": (
        "Landis-Koch band boundary (moderate/substantial). Published reference "
        "value; also quoted as a proposed stricter gold floor."
    ),
    "0.80": "Landis-Koch band boundary (substantial/almost perfect), and the power target.",

    # -- Pre-registered thresholds: src/rubricon/gates/signal.py -------------
    # Declared before results exist. That is the entire point of ADR 0002, so
    # by construction they cannot be sourced from results.
    "0.50": "GatePolicy.alpha_block_below (production). Pre-registered threshold.",
    "0.500": "GatePolicy.alpha_block_below (production). Pre-registered threshold.",
    "0.075": "GatePolicy.max_ci_half_width. Pre-registered threshold.",
    "0.34": "GatePolicy.max_flagged_annotator_fraction. Pre-registered threshold.",
    "0.15": (
        "GatePolicy.max_rubric_gap_rate, EXPLORATORY_POLICY.max_ci_half_width, "
        "the gold-item seeding rate, and the straightlining SD floor. All "
        "declared constants."
    ),
    "0.70": (
        "GatePolicy.min_gold_accuracy, and the judgement-noise multiplier "
        "applied to an anchored pool in annotation/pool.py. Declared constants."
    ),
    "0.30": (
        "EXPLORATORY_POLICY.alpha_block_below and the length-bias probe "
        "tolerance. Pre-registered thresholds."
    ),
    "0.93": "rubric_shortcut probe tolerance, declared in redteam/probes.py.",
    "0.35": (
        "Certification bias threshold (`bias_threshold` in profile_annotators). "
        "Pre-registered protocol constant."
    ),
    "0.90": (
        "Certification threshold: exact-match rate on argument_fidelity. "
        "Protocol constant declared in the calibration protocol."
    ),
    "0.95": (
        "Certification within-one threshold, and the confidence level of every "
        "reported interval. Declared constants."
    ),
    "0.05": (
        "Significance level for the drift permutation test and the power "
        "analysis, and the target effect size in the MDE computation. "
        "Pre-registered constants."
    ),
    "1.0": (
        "GatePolicy.mde_safety_margin, the reference speed_factor, and an "
        "unanchored pool's noise multiplier. Declared constants."
    ),
    "0.025": (
        "Bonferroni-corrected alpha for 2 tests (0.05 / 2). Derived from the "
        "pre-registered significance level, not measured."
    ),
    "0.85": (
        "`unit_label_cost_usd` default in gates/decision.py: the documented "
        "per-label cost assumption used for projected remediation cost. A "
        "declared input, not a measurement."
    ),
    "re:\\$[\\d,]": (
        "Costed remediation lines. Dollar figures and their label counts are "
        "arithmetic over the documented unit label cost (0.85 USD/label, "
        "`unit_label_cost_usd` in gates/decision.py) and the shortfall figures "
        "the results do report; the products themselves are not portfolio "
        "fields. Only numbers on these lines that already failed to trace to "
        "results are covered -- the shortfalls, n_required and MDE values quoted "
        "alongside them are still checked against portfolio.json."
    ),

    # -- Protocol constants declared in the calibration protocol itself ------
    "re:^\\*\\*Stage \\d|^Five stages|^\\*\\*Cadence\\.\\*\\*|"
    "^\\| Gold exact-match rate|^\\| Within-one rate|^\\| Absolute bias|"
    "^\\| Exact-match rate on|^A trainee who misses|^\\*\\*Rate: 0\\.15|"
    "^\\*\\*Composition: |^3\\. \\*\\*Bridge sample": (
        "Onboarding and re-anchoring protocol constants (stage durations, "
        "practice/certification set sizes, certification thresholds, bridge "
        "sample size). Declared in this protocol document; they are inputs to "
        "a programme, not outputs of a run."
    ),
    "re:^\\| Mean annotation duration below the floor": (
        "Straightlining duration floor. A protocol trigger threshold, declared "
        "in stats/drift.py as `speed_floor_s`, not a measurement."
    ),
    "re:^Historical labels become archival": (
        "Bridge-sample size (120 labels per revision), a protocol constant "
        "declared in the calibration protocol."
    ),
    "re:^\\*\\*A small human pilot": (
        "Hypothetical pilot size in an ADR alternatives section. Not a "
        "measurement of anything."
    ),

    # -- Dates ---------------------------------------------------------------
    "re:^Date: ": (
        "ADR authoring date. Reconstructed from working notes; dates are "
        "provenance metadata, not results."
    ),
    "re:^\\*\\*20\\d\\d-\\d\\d-\\d\\d -- ": (
        "Engineering-log entry dates. Provenance metadata, not results."
    ),
}


# --------------------------------------------------------------------------
# configuration
# --------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
PORTFOLIO = REPO_ROOT / "results" / "portfolio.json"
# Secondary result documents. Each is loaded into the same value set when
# present, and named in the header so a reader can see what the docs were
# checked against. `sensitivity.json` is optional only because it is produced by
# `make sensitivity` rather than `make all`; when it is absent the audit says so
# rather than silently narrowing.
SECONDARY_RESULTS = [REPO_ROOT / "results" / "sensitivity.json"]
DOC_ROOT = REPO_ROOT / "docs"
EXTRA_DOCS = ["README.md"]

# Decimal places at which a doc figure may be quoted. A figure written to more
# than four places is compared at four; nothing in this repository is reported
# more precisely than that.
MAX_DP = 4

# Slack allowed when comparing a doc literal against a rounded results value.
# Rounding already does the work; this only absorbs binary float representation
# error (0.1 + 0.2 arithmetic), so it is deliberately tiny.
TOLERANCE = 1e-9

# Years are excluded from the audit, but only after a number has already
# failed to match the results -- see the module docstring on ordering.
YEAR_MIN, YEAR_MAX = 1900, 2100


# --------------------------------------------------------------------------
# building the results value set
# --------------------------------------------------------------------------

# Numbers embedded in strings. The pipeline writes much of its evidence as
# prose ("alpha=0.5841 supports tentative conclusions", "range 0.100, p=0.9170")
# and a document quoting that prose is quoting the results, so those numbers
# have to count as sourced.
_NUM_IN_STRING = re.compile(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?")


def collect_results_values(obj: object, out: set[float]) -> None:
    """Recursively collect every number reachable in the results document."""
    if isinstance(obj, bool):
        return  # bools are ints in Python; they are not quantities
    if isinstance(obj, (int, float)):
        out.add(float(obj))
    elif isinstance(obj, str):
        for m in _NUM_IN_STRING.finditer(obj):
            try:
                out.add(float(m.group()))
            except ValueError:
                pass
    elif isinstance(obj, dict):
        for k, v in obj.items():
            # Keys carry numbers too ("0": 0.088 in a prevalence table).
            collect_results_values(k, out)
            collect_results_values(v, out)
    elif isinstance(obj, list):
        for v in obj:
            collect_results_values(v, out)


def derived_forms(values: set[float]) -> set[float]:
    """Forms a document would plausibly quote for a given results value.

    * the value itself;
    * the percentage form, because rates are recorded as fractions and quoted
      as percentages ("0.7611" -> "76.1 percent");
    * the halved form, because intervals are recorded as full widths and
      quoted as half-widths.
    """
    out: set[float] = set()
    for v in values:
        out.add(v)
        out.add(v * 100.0)
        out.add(v / 2.0)
    return out


def _round_half_up(value: float, dp: int) -> float:
    """Round away from zero at the midpoint, the way a person writing prose does.

    Python's ``round`` is banker's rounding applied to a binary float, so the
    results value 0.6365 becomes 0.636 at three places while an author quoting
    it writes 0.637. That is not a documentation error and it must not be
    reported as one, so both roundings are admitted. The two differ only on
    exact midpoints at the quoted precision, which is the narrowest possible
    widening: it cannot make a stale figure match anything it did not already
    round to.
    """
    q = Decimal(str(value)).quantize(Decimal(1).scaleb(-dp), rounding=ROUND_HALF_UP)
    return float(q)


def build_buckets(values: set[float]) -> dict[int, set[float]]:
    """Pre-round the value set to each precision a document might use."""
    buckets: dict[int, set[float]] = {}
    for dp in range(MAX_DP + 1):
        bucket = {round(v, dp) for v in values}
        bucket |= {_round_half_up(v, dp) for v in values}
        buckets[dp] = bucket
    return buckets


def is_sourced(literal: float, decimals: int, buckets: dict[int, set[float]]) -> bool:
    """Does this literal equal some results value at the literal's precision?"""
    dp = min(decimals, MAX_DP)
    target = round(literal, dp)
    bucket = buckets[dp]
    if target in bucket:
        return True
    # Fallback scan for float-representation edge cases. Cheap enough: this
    # only runs for the minority of literals that miss the exact lookup.
    return any(abs(target - v) <= TOLERANCE for v in bucket)


# --------------------------------------------------------------------------
# extracting numeric literals from prose
# --------------------------------------------------------------------------

_FENCE = re.compile(r"^\s*(```|~~~)")
# A markdown table alignment row: |---|:---:|---:|
_TABLE_RULE = re.compile(r"^\s*\|[\s:\-|]+\|\s*$")
# ISO dates, masked before extraction so 2026-05-02 does not yield 2026, 5, 2.
_ISO_DATE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")
# ADR filenames and cross-references: 0001-versioned-rubrics.md, "ADR 0003".
_ADR_REF = re.compile(r"\bADR[ -]?\d{4}\b|\b\d{4}-[a-z][a-z0-9-]*\.md\b")
# Leading ordinal of a heading ("## 3. Population") or a numbered list item.
_HEADING_ORDINAL = re.compile(r"^(#{1,6}\s+)\d+(?:\.\d+)*\.?\s")
_LIST_ORDINAL = re.compile(r"^(\s*)\d+[.)]\s")
# A bare number, possibly signed, possibly with thousands separators.
_LITERAL = re.compile(r"[-+]?\d[\d,]*(?:\.\d+)?")
# Characters that, immediately before or after a match, mean the digits are
# part of an identifier rather than a quantity: AF-01, sut-baseline-v1, r3,
# agentic-0042, 5xx, Sev-2, 0.15x.
_IDENT_CHARS = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_")


def strip_code_blocks(lines: list[str]) -> list[str]:
    """Blank out fenced code blocks, keeping line numbering intact."""
    out: list[str] = []
    in_fence = False
    for line in lines:
        if _FENCE.match(line):
            in_fence = not in_fence
            out.append("")
            continue
        out.append("" if in_fence else line)
    return out


def mask(text: str, pattern: re.Pattern[str]) -> str:
    """Replace every match with spaces, preserving column positions."""
    return pattern.sub(lambda m: " " * len(m.group()), text)


def literals_in_line(line: str) -> list[tuple[str, float, int]]:
    """Extract quantity-bearing literals from one line of prose.

    Returns (as-written, value, decimal places) triples.
    """
    if _TABLE_RULE.match(line):
        return []

    text = line
    text = mask(text, _ISO_DATE)
    text = mask(text, _ADR_REF)
    text = _HEADING_ORDINAL.sub(lambda m: m.group(1) + " " * (len(m.group()) - len(m.group(1))), text)
    text = _LIST_ORDINAL.sub(lambda m: m.group(1) + " " * (len(m.group()) - len(m.group(1))), text)

    found: list[tuple[str, float, int]] = []
    for m in _LITERAL.finditer(text):
        raw = m.group()
        start, end = m.span()

        # Digits welded to letters or to a hyphenated identifier are not
        # quantities. "AF-01", "sut-candidate-v3", "r3", "5xx", "n=48" is fine
        # because '=' is not an identifier character.
        before = text[start - 1] if start > 0 else ""
        after = text[end] if end < len(text) else ""
        if before in _IDENT_CHARS or after in _IDENT_CHARS:
            continue
        # A sign glued to a preceding digit is a range ("2-3 instances"), not a
        # negative number; the leading operand was already captured separately.
        if raw[0] in "+-" and before.isdigit():
            continue
        # Leading-zero integers are identifiers or ordinals (0001, AF-04's 04).
        body = raw.lstrip("+-")
        if len(body) > 1 and body[0] == "0" and "." not in body:
            continue
        # A digit followed by '.' and then a non-digit is a sentence ordinal.
        if after == "." and "." not in raw:
            nxt = text[end + 1] if end + 1 < len(text) else " "
            if not nxt.isdigit():
                pass  # keep it: "48." at end of a sentence is still a quantity

        try:
            value = float(body.replace(",", "")) * (-1.0 if raw[0] == "-" else 1.0)
        except ValueError:
            continue
        decimals = len(body.split(".")[1]) if "." in body else 0
        found.append((raw, value, decimals))
    return found


# --------------------------------------------------------------------------
# allowlist handling
# --------------------------------------------------------------------------

def split_allowlist() -> tuple[dict[float, str], list[tuple[re.Pattern[str], str]]]:
    """Split ALLOWLIST into exact values and line patterns, validating it."""
    values: dict[float, str] = {}
    patterns: list[tuple[re.Pattern[str], str]] = []
    for key, justification in ALLOWLIST.items():
        if not isinstance(justification, str) or not justification.strip():
            raise SystemExit(
                f"ALLOWLIST entry {key!r} has no justification. Every entry must "
                "say why the number does not come from results; an unjustified "
                "entry defeats the purpose of the audit."
            )
        if key.startswith("re:"):
            patterns.append((re.compile(key[3:]), justification))
        else:
            values[float(key)] = justification
    return values, patterns


def allowlist_hit(
    value: float,
    line: str,
    values: dict[float, str],
    patterns: list[tuple[re.Pattern[str], str]],
) -> str | None:
    """Return the justification if this number is allowlisted, else None."""
    stripped = line.strip()
    for pattern, justification in patterns:
        if pattern.search(stripped):
            return justification
    for allowed, justification in values.items():
        if abs(value - allowed) <= TOLERANCE:
            return justification
    return None


# --------------------------------------------------------------------------
# the audit
# --------------------------------------------------------------------------

def doc_files() -> list[Path]:
    files = sorted(p for p in DOC_ROOT.rglob("*.md")) if DOC_ROOT.is_dir() else []
    for extra in EXTRA_DOCS:
        p = REPO_ROOT / extra
        if p.is_file():
            files.append(p)
    return files


def audit() -> int:
    if not PORTFOLIO.is_file():
        print(f"FATAL: {PORTFOLIO} not found. Run `make run` first.")
        return 1

    raw = PORTFOLIO.read_bytes()
    digest = hashlib.md5(raw).hexdigest()
    portfolio = json.loads(raw)

    base: set[float] = set()
    collect_results_values(portfolio, base)

    secondary: list[tuple[str, str]] = []
    for path in SECONDARY_RESULTS:
        rel = path.relative_to(REPO_ROOT).as_posix()
        if not path.is_file():
            secondary.append((rel, "ABSENT -- its figures cannot be checked"))
            continue
        payload = path.read_bytes()
        collect_results_values(json.loads(payload), base)
        secondary.append((rel, hashlib.md5(payload).hexdigest()))

    buckets = build_buckets(derived_forms(base))
    allow_values, allow_patterns = split_allowlist()

    print("=" * 78)
    print("RUBRICON NUMBER AUDIT")
    print("=" * 78)
    print(f"results/portfolio.json md5 : {digest}")
    for rel, note in secondary:
        print(f"{rel + ' md5':<27}: {note}")
    print(f"distinct results values    : {len(base)}")
    print(f"allowlist entries          : {len(ALLOWLIST)} "
          f"({len(allow_values)} values, {len(allow_patterns)} line patterns)")
    print()

    files = doc_files()
    total_checked = 0
    total_sourced = 0
    total_allowed = 0
    unsourced_by_file: dict[Path, list[tuple[int, str, str]]] = {}

    for path in files:
        lines = strip_code_blocks(path.read_text(encoding="utf-8").splitlines())
        problems: list[tuple[int, str, str]] = []
        checked = sourced = allowed = 0

        for lineno, line in enumerate(lines, start=1):
            for raw, value, decimals in literals_in_line(line):
                checked += 1
                if is_sourced(value, decimals, buckets):
                    sourced += 1
                    continue
                # Value-based exclusions run only on numbers that already
                # failed to trace, so they can never mask a live figure.
                if decimals == 0 and YEAR_MIN <= value <= YEAR_MAX:
                    allowed += 1
                    continue
                if allowlist_hit(value, line, allow_values, allow_patterns):
                    allowed += 1
                    continue
                problems.append((lineno, raw, line.strip()))

        total_checked += checked
        total_sourced += sourced
        total_allowed += allowed
        rel = path.relative_to(REPO_ROOT)
        status = "OK" if not problems else f"{len(problems)} UNSOURCED"
        print(f"{str(rel):<48} {checked:>4} literals  {sourced:>4} sourced  "
              f"{allowed:>3} allowed  {status}")
        if problems:
            unsourced_by_file[rel] = problems

    print()
    if unsourced_by_file:
        print("-" * 78)
        print("UNSOURCED NUMBERS")
        print("-" * 78)
        for rel, problems in unsourced_by_file.items():
            print()
            print(f"{rel}")
            for lineno, raw, context in problems:
                if len(context) > 150:
                    context = context[:147] + "..."
                print(f"  line {lineno:>4}  {raw:>12}   {context}")
        print()

    print("=" * 78)
    print(f"SUMMARY  {total_checked} literals checked | {total_sourced} traced to "
          f"portfolio.json | {total_allowed} allowlisted | "
          f"{sum(len(v) for v in unsourced_by_file.values())} unsourced")
    print("=" * 78)

    if unsourced_by_file:
        print("FAIL: the documentation quotes numbers that do not appear in the "
              "current results.")
        print("      Either correct the document, or -- if the number genuinely "
              "has another")
        print("      source -- add a justified ALLOWLIST entry naming that source.")
        return 1

    print("PASS: every number in the documentation traces to "
          f"portfolio.json (md5 {digest}) or to a justified allowlist entry.")
    return 0


if __name__ == "__main__":
    sys.exit(audit())
